name: CodeExtensionApp
options:
  bundleIdPrefix: com.ryanerkal
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

targets:
  CodeExtensionApp:
    type: application
    platform: macOS
    sources:
      - path: CodeExtensionApp
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ryanerkal.CodeExtensionApp
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_LSUIElement: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Code Extension App"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2025 Ryan Erkal"
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: YES
        MACOSX_DEPLOYMENT_TARGET: "14.0"
